# Initially snatched and adapted from libsodium .travis.yml

sudo: false

language: c

cache: ccache

os:
 - linux

compiler:
 - clang
 - gcc
# - g++

before_script:
 - ./autogen.sh

script:
 - ./configure --disable-dependency-tracking
 - make distcheck
 - make distclean > /dev/null
 - ./configure --disable-dependency-tracking --enable-minimal
 - make distcheck
# - ( echo '#include <magic.h>' ; echo 'int main(void) { magic_t m = magic_open(0); return (m != NULL); }' ) > /tmp/main.c && gcc -Isrc/ $(find src -name '*.c' -o -name '*.S') /tmp/main.c
